FROM endeveit/docker-jq AS build

RUN mkdir /var/mojito

WORKDIR /var/mojito

RUN curl -s https://api.github.com/repos/box/mojito/releases/latest | jq -r '.assets[] | select(.name | startswith("mojito-webapp")) | .browser_download_url' | xargs curl -LO

FROM openjdk:8-jre

RUN apt-get update && apt-get install -y locales

ENV LANG en_US.UTF-8
RUN locale-gen $LANG

RUN mkdir /var/mojito-webapp

WORKDIR /var/mojito-webapp

COPY --from=build /var/mojito/mojito-webapp*.jar mojito-webapp.jar

RUN sh -c 'touch /var/mojito-webapp/mojito-webapp.jar'

RUN ls -lsat /var/mojito-webapp

WORKDIR /var/mojito-webapp

EXPOSE 8080

CMD ["java", "-jar", "mojito-webapp.jar", "-XX:MaxPermSize=128m", "-Xmx4096m", "-Dspring.config.location=/var/mojito-webapp", "-Djava.security.egd=file:/dev/./urandom"]
